
url                      : https://sites.cs.ucsb.edu # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl                  : "/~pconrad" # the subpath of your site, e.g. "/blog"
